# Generated by Django 5.0.2 on 2024-02-27 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0002_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Individual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('mobile', models.IntegerField(max_length=10)),
                ('date', models.DateField(auto_now_add=True)),
                ('slug', models.SlugField(max_length=250, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='types',
            name='slug',
            field=models.SlugField(default='1', max_length=250, unique=True),
            preserve_default=False,
        ),
    ]
