# Generated by Django 5.0.2 on 2024-02-27 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0003_types_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='types',
            name='slug',
        ),
    ]
